[api]
enabled = true
port = 54331
schemas = ["public"]

[db]
port = 54332
shadow_port = 54342
major_version = 17

[studio]
enabled = true
port = 54333

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback", "evenstry://auth/callback", "http://localhost:8081"]

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_OAUTH_CLIENT_ID)"
secret = "env(GOOGLE_OAUTH_CLIENT_SECRET)"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"

[auth.external.apple]
enabled = true
client_id = "com.bertwin.evenstry"
secret = "env(APPLE_OAUTH_CLIENT_SECRET)"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"

[storage]
enabled = true
file_size_limit = "50MiB"

[realtime]
enabled = true

[analytics]
enabled = true
port = 54337

[inbucket]
enabled = true
port = 54334
